# -*- coding: utf-8 -*-
"""moodmirror.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15URMMU4bGFqMksPR5sZo_uqzZViwULOY
"""



# Commented out IPython magic to ensure Python compatibility.
# # %%
# # Write the Streamlit code to a file named moodmirror.py
# %%writefile moodmirror.py
# import streamlit as st
# from transformers import pipeline
#

import streamlit as st
from transformers import pipeline

# Load sentiment analysis model
sentiment_pipeline = pipeline("sentiment-analysis")

# Streamlit app
st.set_page_config(page_title="MoodMirror", layout="centered")
st.title("🧠 MoodMirror – Emotional Health Checker")
st.write("Type a journal entry or message to analyze its emotional tone.")

user_input = st.text_area("Enter your text here:", height=200)

if st.button("Analyze"):
    if user_input.strip() == "":
        st.warning("Please enter some text.")
    else:
        result = sentiment_pipeline(user_input)[0]
        label = result["label"]
        score = result["score"]

        st.subheader("💬 Sentiment Result")
        st.write(f"**Sentiment:** {label} ({score*100:.2f}%)")

        if label == "NEGATIVE":
            st.error("⚠️ Your message indicates distress or negative emotions.")
            st.info("🧘 Tip: Consider talking to someone or taking a short mindfulness break.")
        else:
            st.success("😊 Your message seems positive!")

st.markdown("---")
st.caption("Not a substitute for professional diagnosis.")




